# 05 ? Classifier Two-Sample Test (C2ST) mechanism probe

This is a one-shot exploratory probe, not a confirmation exercise. Notebook 02's ranking result stands regardless of this outcome: C2ST asks only whether a SMOTE-synthetic minority customer is distinguishable from a real minority customer in the flattened honest-window panel feature space.

AUC near 0.5 is a valid result: it means point-level synthetic rows are hard to distinguish from real rows under this probe, and the harm mechanism likely lives elsewhere. AUC meaningfully above 0.5 means the classifier can detect synthetic rows, and permutation importances help locate where that detectability concentrates.

All reusable logic lives in `src/evaluation/c2st.py`; this notebook only orchestrates calls, displays results, and writes the verification report.

## Setup

In [1]:
import hashlib
import inspect
import json
import platform
import sys
from pathlib import Path

import imblearn
import matplotlib
import numpy as np
import pandas as pd
import scipy
import sklearn
from IPython.display import Markdown, display

PROJECT_ROOT = next(
    path for path in [Path.cwd(), *Path.cwd().parents] if (path / "README.md").exists()
)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.data.loaders import SIGNALS, load_churn_panel
from src.evaluation.c2st import (
    build_real_vs_duplicated,
    build_real_vs_synthetic,
    c2st_auc,
    c2st_importances,
)
import src.evaluation.c2st as c2st_module
from src.features.windows import WINDOW_PRESETS
from src.utils.config import OUTPUT_DIR, RAW_CHURN_PATH, SEED, set_global_seed

set_global_seed()

N_SPLITS = 5
N_REPEATS = 3
HONEST_MONTHS = WINDOW_PRESETS["HONEST"]
SIGNALS_USED = SIGNALS

df = load_churn_panel()
print(f"Loaded {len(df):,} rows x {df.shape[1]} columns")
print(f"Honest window: {', '.join(HONEST_MONTHS)}")
print(f"Signals: {', '.join(SIGNALS_USED)}")

Loaded 99,807 rows x 55 columns
Honest window: N-11, N-10, N-9, N-8, N-7, N-6, N-5, N-4, N-3, N-2
Signals: TAG, STATUS_BAYAR, GGN, USAGE

## 1. Build C2ST datasets

The real-vs-SMOTE task uses real churner rows and a balanced sample of newly synthesized SMOTE minority rows. The real-vs-duplicated task uses real churner rows and same-size random duplicated churner rows; this is the sanity floor because copies of real rows should be indistinguishable from real rows.

In [2]:
X_smote, y_smote = build_real_vs_synthetic(
    df, HONEST_MONTHS, signals=SIGNALS_USED, seed=SEED
)
X_dup, y_dup = build_real_vs_duplicated(df, HONEST_MONTHS, signals=SIGNALS_USED, seed=SEED)

metadata = {
    "real_vs_smote": {k: v for k, v in X_smote.attrs.items() if not k.startswith("_")},
    "real_vs_duplicated": {k: v for k, v in X_dup.attrs.items() if not k.startswith("_")},
}

print("real-vs-SMOTE metadata:")
print(json.dumps(metadata["real_vs_smote"], indent=2))
print("\nreal-vs-duplicated metadata:")
print(json.dumps(metadata["real_vs_duplicated"], indent=2))
print(f"\nX_smote shape: {X_smote.shape}, positive_rate={y_smote.mean():.6f}")
print(f"X_dup shape:   {X_dup.shape}, positive_rate={y_dup.mean():.6f}")

real-vs-SMOTE metadata:
{
  "task": "real_vs_smote",
  "n_real": 3804,
  "n_smote_synthetic_total": 92198,
  "n_smote_synthetic_used": 3804,
  "n_features": 40,
  "n_dropped_missing": 1,
  "positive_rate": 0.5,
  "smote_k_neighbors": 5,
  "months": [
    "N-11",
    "N-10",
    "N-9",
    "N-8",
    "N-7",
    "N-6",
    "N-5",
    "N-4",
    "N-3",
    "N-2"
  ],
  "signals": [
    "TAG",
    "STATUS_BAYAR",
    "GGN",
    "USAGE"
  ],
  "log1p_signals": [
    "TAG",
    "USAGE"
  ]
}

real-vs-duplicated metadata:
{
  "task": "real_vs_duplicated",
  "n_real": 3804,
  "n_duplicated": 3804,
  "n_features": 40,
  "n_dropped_missing": 1,
  "positive_rate": 0.5,
  "duplicate_policy": "one_exact_copy_per_real_row",
  "seed": 42,
  "months": [
    "N-11",
    "N-10",
    "N-9",
    "N-8",
    "N-7",
    "N-6",
    "N-5",
    "N-4",
    "N-3",
    "N-2"
  ],
  "signals": [
    "TAG",
    "STATUS_BAYAR",
    "GGN",
    "USAGE"
  ],
  "log1p_signals": [
    "TAG",
    "USAGE"
  ]
}

X_smote shape: (7608, 40), positive_rate=0.500000
X_dup shape:   (7608, 40), positive_rate=0.500000

## 2. C2ST AUC

Rule of thumb: approximately 0.50?0.55 is indistinguishable, 0.55?0.70 is mildly detectable, and above 0.70 is clearly detectable.

In [3]:
smote_auc = c2st_auc(X_smote, y_smote, n_splits=N_SPLITS, n_repeats=N_REPEATS, seed=SEED)
dup_auc = c2st_auc(X_dup, y_dup, n_splits=N_SPLITS, n_repeats=N_REPEATS, seed=SEED)

auc_table = pd.DataFrame(
    {
        "task": ["real_vs_smote", "real_vs_duplicated"],
        "mean_auc": [smote_auc["mean"], dup_auc["mean"]],
        "std_auc": [smote_auc["std"], dup_auc["std"]],
        "se_auc": [smote_auc["se"], dup_auc["se"]],
        "ci_low": [smote_auc["ci_low"], dup_auc["ci_low"]],
        "ci_high": [smote_auc["ci_high"], dup_auc["ci_high"]],
        "n_folds": [smote_auc["n_folds"], dup_auc["n_folds"]],
    }
)
display(auc_table)

print(
    f"real-vs-SMOTE: mean AUC={smote_auc['mean']:.6f} +/- {smote_auc['std']:.6f} "
    f"(95% CI for mean [{smote_auc['ci_low']:.6f}, {smote_auc['ci_high']:.6f}])"
)
print(
    f"real-vs-duplicated: mean AUC={dup_auc['mean']:.6f} +/- {dup_auc['std']:.6f} "
    f"(95% CI for mean [{dup_auc['ci_low']:.6f}, {dup_auc['ci_high']:.6f}])"
)

,task,mean_auc,std_auc,se_auc,ci_low,ci_high,n_folds
0,real_vs_smote,0.860849,0.007294,0.001883,0.857158,0.86454,15
1,real_vs_duplicated,0.500000,0.000000,0.000000,0.500000,0.50000,15

real-vs-SMOTE: mean AUC=0.860849 +/- 0.007294 (95% CI for mean [0.857158, 0.864540])
real-vs-duplicated: mean AUC=0.500000 +/- 0.000000 (95% CI for mean [0.500000, 0.500000])

## 3. Permutation importances

In [4]:
smote_importances = c2st_importances(X_smote, y_smote, seed=SEED)
top_importances = smote_importances.head(20).copy()
display(top_importances)

             feature  importance_mean  importance_std
0            TAG_N-2         0.033191        0.004055
1            TAG_N-7         0.020795        0.003114
2   STATUS_BAYAR_N-2         0.018470        0.003291
3            TAG_N-3         0.017293        0.002423
4   STATUS_BAYAR_N-6         0.017047        0.002214
5            TAG_N-8         0.014627        0.002595
6            GGN_N-3         0.014468        0.002638
7            TAG_N-4         0.011284        0.003101
8            GGN_N-4         0.010838        0.002382
9          USAGE_N-4         0.010278        0.003153
10  STATUS_BAYAR_N-3         0.010123        0.002144
11         USAGE_N-6         0.009626        0.004343
12           TAG_N-5         0.008698        0.002369
13          TAG_N-10         0.007638        0.001634
14  STATUS_BAYAR_N-4         0.007334        0.001696
15           TAG_N-6         0.007037        0.002682
16           TAG_N-9         0.005694        0.001437
17           GGN_N-6         0.005594        0.002759
18         USAGE_N-5         0.004959        0.003457
19           GGN_N-7         0.004768        0.002386

## 4. Interpretation

In [5]:
def _auc_label(mean_auc: float) -> str:
    if mean_auc <= 0.55:
        return "indistinguishable"
    if mean_auc <= 0.70:
        return "mildly detectable"
    return "clearly detectable"

smote_label = _auc_label(smote_auc["mean"])
dup_label = _auc_label(dup_auc["mean"])

if smote_auc["mean"] > 0.55:
    importance_sentence = (
        "Because the real-vs-SMOTE AUC is meaningfully above 0.55, the top "
        "permutation importances are interpreted as evidence about where point-level "
        "synthetic detectability concentrates."
    )
else:
    importance_sentence = (
        "Because the real-vs-SMOTE AUC is near the indistinguishable range, the "
        "permutation importances are reported for transparency but should not be "
        "treated as a stable mechanism explanation."
    )

interpretation = f"""
**C2ST result.** The real-vs-SMOTE classifier has mean ROC-AUC {smote_auc['mean']:.4f} (std {smote_auc['std']:.4f}; 95% CI for the mean [{smote_auc['ci_low']:.4f}, {smote_auc['ci_high']:.4f}]), which is **{smote_label}** by the notebook's rule of thumb.

**Sanity floor.** The real-vs-duplicated classifier has mean ROC-AUC {dup_auc['mean']:.4f} (std {dup_auc['std']:.4f}), which is **{dup_label}**. Since duplicated rows are copies of real rows, this checks that the C2ST harness is not spuriously detecting differences when none should exist.

{importance_sentence}

**Scope.** C2ST asks whether complete flattened minority customers are point-level distinguishable from synthetic ones across all selected signals and honest-window lags. It does not test ranking performance, calibration, threshold effects, or causal mechanism by itself. Notebook 02's finding that SMOTE harms PR-AUC on the honest window remains the ranking evidence; this notebook only probes one possible explanation. If C2ST is inconclusive, the mechanism remains open rather than disproven.
"""

display(Markdown(interpretation))

**C2ST result.** The real-vs-SMOTE classifier has mean ROC-AUC 0.8608 (std 0.0073; 95% CI for the mean [0.8572, 0.8645]), which is **clearly detectable** by the notebook's rule of thumb.

**Sanity floor.** The real-vs-duplicated classifier has mean ROC-AUC 0.5000 (std 0.0000), which is **indistinguishable**. Since duplicated rows are copies of real rows, this checks that the C2ST harness is not spuriously detecting differences when none should exist.

Because the real-vs-SMOTE AUC is meaningfully above 0.55, the top permutation importances are interpreted as evidence about where point-level synthetic detectability concentrates.

**Scope.** C2ST asks whether complete flattened minority customers are point-level distinguishable from synthetic ones across all selected signals and honest-window lags. It does not test ranking performance, calibration, threshold effects, or causal mechanism by itself. Notebook 02's finding that SMOTE harms PR-AUC on the honest window remains the ranking evidence; this notebook only probes one possible explanation. If C2ST is inconclusive, the mechanism remains open rather than disproven.

## 5. Verification report

In [6]:
def _df_to_md_table(frame: pd.DataFrame, float_format: str = "{:.6f}") -> str:
    header = "| " + " | ".join([frame.index.name or ""] + list(frame.columns)) + " |"
    sep = "| " + " | ".join(["---"] * (len(frame.columns) + 1)) + " |"
    lines = [header, sep]
    for idx, row in frame.iterrows():
        row_cells = [str(idx)]
        for value in row:
            if isinstance(value, (float, np.floating)):
                row_cells.append(float_format.format(float(value)))
            else:
                row_cells.append(str(value))
        lines.append("| " + " | ".join(row_cells) + " |")
    return "\n".join(lines)


def _present(value: float) -> bool:
    return bool(np.isfinite(value))


smote_balance = float(y_smote.mean())
dup_balance = float(y_dup.mean())
dup_auc_pass = 0.47 <= dup_auc["mean"] <= 0.53
balance_pass = 0.45 <= smote_balance <= 0.55 and 0.45 <= dup_balance <= 0.55
uncertainty_present = all(
    _present(value)
    for value in [smote_auc["mean"], smote_auc["std"], smote_auc["ci_low"], smote_auc["ci_high"]]
)

checks = [
    {
        "check": "real-vs-duplicated C2ST AUC in [0.47, 0.53]",
        "measured": f"{dup_auc['mean']:.6f}",
        "target": "0.47 <= AUC <= 0.53",
        "result": "PASS" if dup_auc_pass else "FAIL",
    },
    {
        "check": "C2ST tasks are class-balanced within [0.45, 0.55] positive rate",
        "measured": f"real_vs_smote={smote_balance:.6f}, real_vs_duplicated={dup_balance:.6f}",
        "target": "both positive rates in [0.45, 0.55]",
        "result": "PASS" if balance_pass else "FAIL",
    },
    {
        "check": "real-vs-SMOTE AUC and 95% interval are reported",
        "measured": (
            f"mean={smote_auc['mean']:.6f}, std={smote_auc['std']:.6f}, "
            f"ci=[{smote_auc['ci_low']:.6f}, {smote_auc['ci_high']:.6f}]"
        ),
        "target": "reported; no PASS/FAIL on AUC value",
        "result": "PASS" if uncertainty_present else "FAIL",
    },
]
checks_table = pd.DataFrame(checks)
for check in checks:
    print(
        f"[{check['result']}] {check['check']} | measured: {check['measured']} | "
        f"target: {check['target']}"
    )

[PASS] real-vs-duplicated C2ST AUC in [0.47, 0.53] | measured: 0.500000 | target: 0.47 <= AUC <= 0.53
[PASS] C2ST tasks are class-balanced within [0.45, 0.55] positive rate | measured: real_vs_smote=0.500000, real_vs_duplicated=0.500000 | target: both positive rates in [0.45, 0.55]
[PASS] real-vs-SMOTE AUC and 95% interval are reported | measured: mean=0.860849, std=0.007294, ci=[0.857158, 0.864540] | target: reported; no PASS/FAIL on AUC value

In [7]:
c2st_source = inspect.getsource(c2st_module)
file_sha256_12 = hashlib.sha256(RAW_CHURN_PATH.read_bytes()).hexdigest()[:12]

auc_report_table = auc_table.set_index("task")
importance_report_table = top_importances.set_index("feature")
checks_report_table = checks_table.set_index("check")

raw_auc_json = json.dumps(auc_report_table.to_dict(orient="index"), indent=2)
raw_importance_json = json.dumps(top_importances.to_dict(orient="records"), indent=2)
raw_metadata_json = json.dumps(metadata, indent=2)

report_lines = [
    "# 05 ? C2ST Mechanism Probe Verification Report",
    "",
    "## Environment",
    f"- Python: {platform.python_version()}",
    f"- numpy: {np.__version__}",
    f"- pandas: {pd.__version__}",
    f"- scikit-learn: {sklearn.__version__}",
    f"- imbalanced-learn: {imblearn.__version__}",
    f"- scipy: {scipy.__version__}",
    f"- matplotlib: {matplotlib.__version__}",
    f"- Seed: {SEED}",
    f"- Raw data SHA256(first 12): {file_sha256_12}",
    "",
    "## CV config",
    f"- n_splits: {N_SPLITS}",
    f"- n_repeats: {N_REPEATS}",
    f"- n_folds per task: {smote_auc['n_folds']}",
    "- Classifier: src.models.factory.make_gbm",
    "",
    "## Group sizes and task balance",
    f"- n_real: {metadata['real_vs_smote']['n_real']:,}",
    f"- n_smote_synthetic_total: {metadata['real_vs_smote']['n_smote_synthetic_total']:,}",
    f"- n_smote_synthetic_used: {metadata['real_vs_smote']['n_smote_synthetic_used']:,}",
    f"- n_duplicated: {metadata['real_vs_duplicated']['n_duplicated']:,}",
    f"- n_dropped_missing before C2ST construction: {metadata['real_vs_smote']['n_dropped_missing']}",
    f"- real-vs-SMOTE positive_rate: {smote_balance:.6f}",
    f"- real-vs-duplicated positive_rate: {dup_balance:.6f}",
    "",
    "Raw metadata JSON:",
    "```json",
    raw_metadata_json,
    "```",
    "",
    "## C2ST AUC table (full precision)",
    "",
    _df_to_md_table(auc_report_table),
    "",
    "Raw JSON:",
    "```json",
    raw_auc_json,
    "```",
    "",
    "## Top permutation importances (real-vs-SMOTE)",
    "",
    _df_to_md_table(importance_report_table),
    "",
    "Raw JSON:",
    "```json",
    raw_importance_json,
    "```",
    "",
    "## Interpretation",
    interpretation.strip(),
    "",
    "## Inline source",
    "",
    "### src/evaluation/c2st.py",
    "```python",
    c2st_source,
    "```",
    "",
    "## Self-run acceptance checks",
    _df_to_md_table(checks_report_table, float_format="{}"),
    "",
]

report_text = "\n".join(report_lines)
report_path = OUTPUT_DIR / "05_c2st_verification.md"
report_path.write_text(report_text, encoding="utf-8")
print(report_text)

# 05 ? C2ST Mechanism Probe Verification Report

## Environment
- Python: 3.12.3
- numpy: 2.4.6
- pandas: 3.0.3
- scikit-learn: 1.9.0
- imbalanced-learn: 0.14.2
- scipy: 1.18.0
- matplotlib: 3.11.0
- Seed: 42
- Raw data SHA256(first 12): c04f3a55aa4f

## CV config
- n_splits: 5
- n_repeats: 3
- n_folds per task: 15
- Classifier: src.models.factory.make_gbm

## Group sizes and task balance
- n_real: 3,804
- n_smote_synthetic_total: 92,198
- n_smote_synthetic_used: 3,804
- n_duplicated: 3,804
- n_dropped_missing before C2ST construction: 1
- real-vs-SMOTE positive_rate: 0.500000
- real-vs-duplicated positive_rate: 0.500000

Raw metadata JSON:
```json
{
  "real_vs_smote": {
    "task": "real_vs_smote",
    "n_real": 3804,
    "n_smote_synthetic_total": 92198,
    "n_smote_synthetic_used": 3804,
    "n_features": 40,
    "n_dropped_missing": 1,
    "positive_rate": 0.5,
    "smote_k_neighbors": 5,
    "months": [
      "N-11",
      "N-10",
      "N-9",
      "N-8",
      "N-7",
      "N-6",
      "N-5",
      "N-4",
      "N-3",
      "N-2"
    ],
    "signals": [
      "TAG",
      "STATUS_BAYAR",
      "GGN",
      "USAGE"
    ],
    "log1p_signals": [
      "TAG",
      "USAGE"
    ]
  },
  "real_vs_duplicated": {
    "task": "real_vs_duplicated",
    "n_real": 3804,
    "n_duplicated": 3804,
    "n_features": 40,
    "n_dropped_missing": 1,
    "positive_rate": 0.5,
    "duplicate_policy": "one_exact_copy_per_real_row",
    "seed": 42,
    "months": [
      "N-11",
      "N-10",
      "N-9",
      "N-8",
      "N-7",
      "N-6",
      "N-5",
      "N-4",
      "N-3",
      "N-2"
    ],
    "signals": [
      "TAG",
      "STATUS_BAYAR",
      "GGN",
      "USAGE"
    ],
    "log1p_signals": [
      "TAG",
      "USAGE"
    ]
  }
}
```

## C2ST AUC table (full precision)

| task | mean_auc | std_auc | se_auc | ci_low | ci_high | n_folds |
| --- | --- | --- | --- | --- | --- | --- |
| real_vs_smote | 0.860849 | 0.007294 | 0.001883 | 0.857158 | 0.864540 | 15.000000 |
| real_vs_duplicated | 0.500000 | 0.000000 | 0.000000 | 0.500000 | 0.500000 | 15.000000 |

Raw JSON:
```json
{
  "real_vs_smote": {
    "mean_auc": 0.860848986441854,
    "std_auc": 0.0072939909742117835,
    "se_auc": 0.0018833003713672966,
    "ci_low": 0.8571577177139741,
    "ci_high": 0.864540255169734,
    "n_folds": 15
  },
  "real_vs_duplicated": {
    "mean_auc": 0.5,
    "std_auc": 0.0,
    "se_auc": 0.0,
    "ci_low": 0.5,
    "ci_high": 0.5,
    "n_folds": 15
  }
}
```

## Top permutation importances (real-vs-SMOTE)

| feature | importance_mean | importance_std |
| --- | --- | --- |
| TAG_N-2 | 0.033191 | 0.004055 |
| TAG_N-7 | 0.020795 | 0.003114 |
| STATUS_BAYAR_N-2 | 0.018470 | 0.003291 |
| TAG_N-3 | 0.017293 | 0.002423 |
| STATUS_BAYAR_N-6 | 0.017047 | 0.002214 |
| TAG_N-8 | 0.014627 | 0.002595 |
| GGN_N-3 | 0.014468 | 0.002638 |
| TAG_N-4 | 0.011284 | 0.003101 |
| GGN_N-4 | 0.010838 | 0.002382 |
| USAGE_N-4 | 0.010278 | 0.003153 |
| STATUS_BAYAR_N-3 | 0.010123 | 0.002144 |
| USAGE_N-6 | 0.009626 | 0.004343 |
| TAG_N-5 | 0.008698 | 0.002369 |
| TAG_N-10 | 0.007638 | 0.001634 |
| STATUS_BAYAR_N-4 | 0.007334 | 0.001696 |
| TAG_N-6 | 0.007037 | 0.002682 |
| TAG_N-9 | 0.005694 | 0.001437 |
| GGN_N-6 | 0.005594 | 0.002759 |
| USAGE_N-5 | 0.004959 | 0.003457 |
| GGN_N-7 | 0.004768 | 0.002386 |

Raw JSON:
```json
[
  {
    "feature": "TAG_N-2",
    "importance_mean": 0.03319147148222963,
    "importance_std": 0.0040549043334085445
  },
  {
    "feature": "TAG_N-7",
    "importance_mean": 0.020794647507023933,
    "importance_std": 0.0031141318974327904
  },
  {
    "feature": "STATUS_BAYAR_N-2",
    "importance_mean": 0.018469904389756275,
    "importance_std": 0.0032914080005148325
  },
  {
    "feature": "TAG_N-3",
    "importance_mean": 0.017292550538975514,
    "importance_std": 0.0024234863757175637
  },
  {
    "feature": "STATUS_BAYAR_N-6",
    "importance_mean": 0.017047415913958495,
    "importance_std": 0.0022139278699590498
  },
  {
    "feature": "TAG_N-8",
    "importance_mean": 0.014627139952299906,
    "importance_std": 0.0025946349737656195
  },
  {
    "feature": "GGN_N-3",
    "importance_mean": 0.014468360826668646,
    "importance_std": 0.0026380928684474865
  },
  {
    "feature": "TAG_N-4",
    "importance_mean": 0.011284043250726138,
    "importance_std": 0.0031014229219077016
  },
  {
    "feature": "GGN_N-4",
    "importance_mean": 0.010837836313759031,
    "importance_std": 0.0023819165514914697
  },
  {
    "feature": "USAGE_N-4",
    "importance_mean": 0.010278294694499434,
    "importance_std": 0.0031529460657686212
  },
  {
    "feature": "STATUS_BAYAR_N-3",
    "importance_mean": 0.010123385533629414,
    "importance_std": 0.002143914840549929
  },
  {
    "feature": "USAGE_N-6",
    "importance_mean": 0.009625763350549122,
    "importance_std": 0.004343259793529594
  },
  {
    "feature": "TAG_N-5",
    "importance_mean": 0.008697745800811807,
    "importance_std": 0.002369324494717417
  },
  {
    "feature": "TAG_N-10",
    "importance_mean": 0.007637762452717289,
    "importance_std": 0.001634185923882242
  },
  {
    "feature": "STATUS_BAYAR_N-4",
    "importance_mean": 0.0073338596485408416,
    "importance_std": 0.0016958960296023717
  },
  {
    "feature": "TAG_N-6",
    "importance_mean": 0.0070367016400910585,
    "importance_std": 0.0026820358175127187
  },
  {
    "feature": "TAG_N-9",
    "importance_mean": 0.005694487290482819,
    "importance_std": 0.001437331782740388
  },
  {
    "feature": "GGN_N-6",
    "importance_mean": 0.005594255203167586,
    "importance_std": 0.0027587168712291795
  },
  {
    "feature": "USAGE_N-5",
    "importance_mean": 0.004959249271064526,
    "importance_std": 0.0034571896423255728
  },
  {
    "feature": "GGN_N-7",
    "importance_mean": 0.004767796585806461,
    "importance_std": 0.0023863076490239694
  }
]
```

## Interpretation
**C2ST result.** The real-vs-SMOTE classifier has mean ROC-AUC 0.8608 (std 0.0073; 95% CI for the mean [0.8572, 0.8645]), which is **clearly detectable** by the notebook's rule of thumb.

**Sanity floor.** The real-vs-duplicated classifier has mean ROC-AUC 0.5000 (std 0.0000), which is **indistinguishable**. Since duplicated rows are copies of real rows, this checks that the C2ST harness is not spuriously detecting differences when none should exist.

Because the real-vs-SMOTE AUC is meaningfully above 0.55, the top permutation importances are interpreted as evidence about where point-level synthetic detectability concentrates.

**Scope.** C2ST asks whether complete flattened minority customers are point-level distinguishable from synthetic ones across all selected signals and honest-window lags. It does not test ranking performance, calibration, threshold effects, or causal mechanism by itself. Notebook 02's finding that SMOTE harms PR-AUC on the honest window remains the ranking evidence; this notebook only probes one possible explanation. If C2ST is inconclusive, the mechanism remains open rather than disproven.

## Inline source

### src/evaluation/c2st.py
```python
"""Classifier two-sample tests for real vs. synthetic minority examples."""

import numpy as np
import pandas as pd
from imblearn.over_sampling import SMOTE
from sklearn.inspection import permutation_importance
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import RepeatedStratifiedKFold, StratifiedGroupKFold, train_test_split

from src.data.loaders import SIGNALS
from src.models.factory import make_gbm
from src.utils.config import SEED

LOG1P_SIGNALS: tuple[str, ...] = ("TAG", "USAGE")


def _panel_feature_frame(
    df: pd.DataFrame,
    months: list[str],
    signals: tuple[str, ...] = SIGNALS,
) -> pd.DataFrame:
    """Build the flattened panel-lag representation used by C2ST.

    The feature space contains only panel signal lags, not static customer
    fields. ``TAG`` and ``USAGE`` are transformed with ``log1p`` to match the
    prior preprocessing choice for sparse/high-range activity signals; the
    bounded/status-like ``STATUS_BAYAR`` and ``GGN`` signals are left on their
    original scale.

    Args:
        df: Raw churn panel.
        months: Chronologically ordered month labels to include.
        signals: Signal names to include.

    Returns:
        DataFrame with columns named ``{signal}_{month}``.
    """
    columns = [f"{signal}_{month}" for signal in signals for month in months]
    X = df[columns].copy()
    for signal in signals:
        if signal in LOG1P_SIGNALS:
            signal_cols = [f"{signal}_{month}" for month in months]
            X[signal_cols] = np.log1p(X[signal_cols])
    return X


def _drop_rows_with_missing(X: pd.DataFrame, y: np.ndarray) -> tuple[pd.DataFrame, np.ndarray, int]:
    """Drop rows with missing C2ST features before distance-based SMOTE."""
    missing_rows = X.isna().any(axis=1).to_numpy()
    return X.loc[~missing_rows].reset_index(drop=True), y[~missing_rows], int(missing_rows.sum())


def _as_feature_frame(X: pd.DataFrame | np.ndarray) -> pd.DataFrame:
    """Return a numeric feature DataFrame with stable column names."""
    if isinstance(X, pd.DataFrame):
        return X.reset_index(drop=True).copy()
    array = np.asarray(X)
    columns = [f"feature_{idx}" for idx in range(array.shape[1])]
    return pd.DataFrame(array, columns=columns)


def build_real_vs_synthetic_xy(
    X: pd.DataFrame | np.ndarray,
    y: np.ndarray,
    seed: int = SEED,
) -> tuple[pd.DataFrame, np.ndarray, dict]:
    """Build a balanced real-minority vs SMOTE-synthetic C2ST dataset.

    Args:
        X: Feature matrix for a binary classification dataset.
        y: Binary target array; the minority/positive class must be labeled
            ``1``.
        seed: Random seed for SMOTE and synthetic-row subsampling.

    Returns:
        Tuple ``(X_c2st, y_c2st, meta)`` where real minority rows are labeled
        ``0`` and newly synthesized SMOTE minority rows are labeled ``1``.
        The task is balanced by subsampling synthetic rows down to the real
        minority count.
    """
    X_all = _as_feature_frame(X)
    y_array = np.asarray(y)
    X_all, y_array, n_dropped_missing = _drop_rows_with_missing(X_all, y_array)

    real = X_all.loc[y_array == 1].reset_index(drop=True)
    if len(real) < 2:
        raise ValueError("C2ST requires at least two real minority examples.")

    k_neighbors = min(5, len(real) - 1)
    smote = SMOTE(random_state=seed, k_neighbors=k_neighbors)
    X_resampled, y_resampled = smote.fit_resample(X_all, y_array)

    n_original = len(X_all)
    if not np.allclose(np.asarray(X_resampled.iloc[:n_original]), np.asarray(X_all)):
        raise AssertionError("SMOTE did not preserve original rows as the resampled prefix.")
    if not np.array_equal(np.asarray(y_resampled[:n_original]), y_array):
        raise AssertionError("SMOTE did not preserve original labels as the resampled prefix.")

    synthetic_all = X_resampled.iloc[n_original:].reset_index(drop=True)
    rng = np.random.default_rng(seed)
    synthetic_idx = rng.choice(len(synthetic_all), size=len(real), replace=False)
    synthetic = synthetic_all.iloc[synthetic_idx].reset_index(drop=True)

    X_c2st = pd.concat([real, synthetic], ignore_index=True)
    y_c2st = np.r_[np.zeros(len(real), dtype=int), np.ones(len(synthetic), dtype=int)]
    groups = np.arange(len(X_c2st))
    meta = {
        "task": "real_vs_smote",
        "n_real": int(len(real)),
        "n_smote_synthetic_total": int(len(synthetic_all)),
        "n_smote_synthetic_used": int(len(synthetic)),
        "n_features": int(X_c2st.shape[1]),
        "n_dropped_missing": n_dropped_missing,
        "positive_rate": float(np.mean(y_c2st)),
        "smote_k_neighbors": int(k_neighbors),
    }
    X_c2st.attrs.update({**meta, "_groups": groups})
    return X_c2st, y_c2st, meta


def build_real_vs_duplicated_xy(
    X: pd.DataFrame | np.ndarray,
    y: np.ndarray,
    seed: int = SEED,
) -> tuple[pd.DataFrame, np.ndarray, dict]:
    """Build a balanced real-minority vs exact-copy C2ST sanity task.

    Args:
        X: Feature matrix for a binary classification dataset.
        y: Binary target array; the minority/positive class must be labeled
            ``1``.
        seed: Random seed, stored for reproducibility metadata.

    Returns:
        Tuple ``(X_c2st, y_c2st, meta)`` where real minority rows are labeled
        ``0`` and exact copies are labeled ``1``. Group IDs keep each
        original/copy pair in the same CV fold, making the expected AUC 0.5.
    """
    X_all = _as_feature_frame(X)
    y_array = np.asarray(y)
    X_all, y_array, n_dropped_missing = _drop_rows_with_missing(X_all, y_array)

    real = X_all.loc[y_array == 1].reset_index(drop=True)
    duplicated = real.copy()

    X_c2st = pd.concat([real, duplicated], ignore_index=True)
    y_c2st = np.r_[np.zeros(len(real), dtype=int), np.ones(len(duplicated), dtype=int)]
    groups = np.r_[np.arange(len(real)), np.arange(len(duplicated))]
    meta = {
        "task": "real_vs_duplicated",
        "n_real": int(len(real)),
        "n_duplicated": int(len(duplicated)),
        "n_features": int(X_c2st.shape[1]),
        "n_dropped_missing": n_dropped_missing,
        "positive_rate": float(np.mean(y_c2st)),
        "duplicate_policy": "one_exact_copy_per_real_row",
        "seed": int(seed),
    }
    X_c2st.attrs.update({**meta, "_groups": groups})
    return X_c2st, y_c2st, meta


def build_real_vs_synthetic(
    df: pd.DataFrame,
    months: list[str],
    signals: tuple[str, ...] = SIGNALS,
    seed: int = SEED,
) -> tuple[pd.DataFrame, np.ndarray]:
    """Build a balanced real-minority vs SMOTE-synthetic C2ST dataset.

    The returned task is balanced by subsampling the newly synthesized SMOTE
    rows down to the number of real minority rows. Full pre-subsampling group
    sizes and preprocessing details are stored in ``X.attrs`` for reporting.

    Args:
        df: Raw churn panel with ``CHURN`` target and panel signal columns.
        months: Chronologically ordered month labels to include.
        signals: Signal names to include.
        seed: Random seed for SMOTE and synthetic-row subsampling.

    Returns:
        Tuple ``(X, y_c2st)`` where real minority rows are labeled ``0`` and
        SMOTE-synthetic rows are labeled ``1``.
    """
    X_all = _panel_feature_frame(df, months, signals)
    X_c2st, y_c2st, meta = build_real_vs_synthetic_xy(X_all, df["CHURN"].to_numpy(), seed=seed)
    X_c2st.attrs.update(
        {
            **meta,
            "task": "real_vs_smote",
            "months": list(months),
            "signals": list(signals),
            "log1p_signals": [signal for signal in signals if signal in LOG1P_SIGNALS],
        }
    )
    return X_c2st, y_c2st


def build_real_vs_duplicated(
    df: pd.DataFrame,
    months: list[str],
    signals: tuple[str, ...] = SIGNALS,
    seed: int = SEED,
) -> tuple[pd.DataFrame, np.ndarray]:
    """Build a balanced real-minority vs duplicated-minority C2ST dataset.

    Duplicated rows are one exact copy of every real minority row. This is
    the sanity floor: the classifier should not be able to distinguish a row
    from an identical copy of that same row. Sampling duplicates with
    replacement would introduce finite-sample multiplicity artifacts, which
    are not the mechanism being tested here.

    Args:
        df: Raw churn panel with ``CHURN`` target and panel signal columns.
        months: Chronologically ordered month labels to include.
        signals: Signal names to include.
        seed: Random seed, stored for reproducibility metadata.

    Returns:
        Tuple ``(X, y_c2st)`` where real minority rows are labeled ``0`` and
        duplicated rows are labeled ``1``.
    """
    X_all = _panel_feature_frame(df, months, signals)
    X_c2st, y_c2st, meta = build_real_vs_duplicated_xy(X_all, df["CHURN"].to_numpy(), seed=seed)
    X_c2st.attrs.update(
        {
            **meta,
            "task": "real_vs_duplicated",
            "months": list(months),
            "signals": list(signals),
            "log1p_signals": [signal for signal in signals if signal in LOG1P_SIGNALS],
        }
    )
    return X_c2st, y_c2st


def _repeated_splits(
    X: pd.DataFrame,
    y_c2st: np.ndarray,
    n_splits: int,
    n_repeats: int,
    seed: int,
):
    """Yield repeated stratified splits, grouped when C2ST pairs are present."""
    groups = X.attrs.get("_groups")
    if groups is None:
        splitter = RepeatedStratifiedKFold(
            n_splits=n_splits, n_repeats=n_repeats, random_state=seed
        )
        yield from splitter.split(X, y_c2st)
        return

    groups = np.asarray(groups)
    for repeat in range(n_repeats):
        splitter = StratifiedGroupKFold(n_splits=n_splits, shuffle=True, random_state=seed + repeat)
        yield from splitter.split(X, y_c2st, groups=groups)


def c2st_auc(
    X: pd.DataFrame,
    y_c2st: np.ndarray,
    n_splits: int = 5,
    n_repeats: int = 3,
    seed: int = SEED,
) -> dict:
    """Estimate C2ST ROC-AUC with repeated stratified cross-validation.

    Args:
        X: C2ST feature matrix.
        y_c2st: Binary C2ST labels, with synthetic/copy rows labeled ``1``.
        n_splits: Number of folds per repeat.
        n_repeats: Number of repeated CV rounds.
        seed: Random seed for the splitter and model.

    Returns:
        Dict with per-fold AUCs, mean, standard deviation, standard error,
        and normal-approximation 95% interval for the mean.
    """
    rows = []
    for fold_i, (train_idx, test_idx) in enumerate(
        _repeated_splits(X, y_c2st, n_splits, n_repeats, seed)
    ):
        model = make_gbm(random_state=seed)
        model.fit(X.iloc[train_idx], y_c2st[train_idx])
        scores = model.predict_proba(X.iloc[test_idx])[:, 1]
        rows.append(
            {
                "repeat": int(fold_i // n_splits),
                "fold": int(fold_i % n_splits),
                "roc_auc": float(roc_auc_score(y_c2st[test_idx], scores)),
            }
        )

    fold_results = pd.DataFrame(rows)
    aucs = fold_results["roc_auc"].to_numpy()
    std = float(np.std(aucs, ddof=1)) if len(aucs) > 1 else float("nan")
    se = float(std / np.sqrt(len(aucs))) if len(aucs) > 1 else float("nan")
    mean = float(np.mean(aucs))
    return {
        "fold_results": fold_results,
        "aucs": aucs,
        "mean": mean,
        "std": std,
        "se": se,
        "ci_low": float(mean - 1.96 * se),
        "ci_high": float(mean + 1.96 * se),
        "n_folds": int(len(aucs)),
    }


def c2st_importances(
    X: pd.DataFrame,
    y_c2st: np.ndarray,
    seed: int = SEED,
) -> pd.DataFrame:
    """Compute held-out permutation importances for the C2ST classifier.

    Args:
        X: C2ST feature matrix.
        y_c2st: Binary C2ST labels, with synthetic rows labeled ``1``.
        seed: Random seed for the train/test split, model, and permutations.

    Returns:
        DataFrame sorted by decreasing mean permutation importance.
    """
    X_train, X_test, y_train, y_test = train_test_split(
        X, y_c2st, test_size=0.25, stratify=y_c2st, random_state=seed
    )
    model = make_gbm(random_state=seed)
    model.fit(X_train, y_train)
    result = permutation_importance(
        model,
        X_test,
        y_test,
        scoring="roc_auc",
        n_repeats=10,
        random_state=seed,
        n_jobs=1,
    )
    importances = pd.DataFrame(
        {
            "feature": X.columns,
            "importance_mean": result.importances_mean,
            "importance_std": result.importances_std,
        }
    )
    return importances.sort_values("importance_mean", ascending=False).reset_index(drop=True)

```

## Self-run acceptance checks
| check | measured | target | result |
| --- | --- | --- | --- |
| real-vs-duplicated C2ST AUC in [0.47, 0.53] | 0.500000 | 0.47 <= AUC <= 0.53 | PASS |